5.Django/ClassBaseView/ClassBaseView/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view()),
    path('basic_app/',include('basic_app.urls',namespace='basic_app')),
]

5.Django/ClassBaseView/basic_app/urls.py
from django.urls import path
from . import views
app_name = 'basic_app'

urlpatterns =[
    path('',views.SchoolListView.as_view(),name='list'),
    path('<int:pk>/',views.SchoolDetailView.as_view(),name='detail'),
    path('create/',views.SchoolCreateView.as_view(),name ='create'),
    path('update/<int:pk>/',views.SchoolUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.SchoolDeleteView.as_view(),name='delete'),
]

5.Django/ClassBaseView/basic_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})

    
class Student(models.Model):
    name = models.CharField(max_length=256)    
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete = models.CASCADE)

    def __str__(self):
        return self.name

5.Django/ClassBaseView/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from . import models
from django.urls import reverse_lazy
# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'BASIC INJECYION!'
        return context

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    # school_list 


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'


    
class SchoolCreateView(CreateView):
    model = models.School
    fields =('name','principal','location')
    
class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

5.Django/ClassBaseView/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
      CBVs
      {# Title Extensions go inside the block#}
      {% block title_block %}

      {% endblock %}
    </title>

    {# Bootstrap and CSS (Probably would want downloaded files in your real projects)#}
    {# https://bootswatch.com/#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="#"></a>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

  {# Plugins#}


  <!-- Latest compiled and minified jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</html>

5.Django/ClassBaseView/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html"%}
{% block body_block%}
<h1>
    Delete {{school.name}} ?
</h1>
<form action="" method="POST">

    {%csrf_token%}
    <input type="submit" value="Delete" class="btn btn-danger">
    <a href="{% url 'basic_app:detail' pk=school.pk%}" class="btn btn-success">Cancel</a>
</form>

{%endblock%}

5.Django/ClassBaseView/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html"%}
{% block body_block%}
<div class="jumbotron">
    <h1>Welcome to the School Detail Page!</h1>
    <h2>School details:</h2>
    <p>Name : {{school_detail.name}}</p>
    <p>Principal : {{school_detail.principal}}</p>
    <p>Locaction : {{school_detail.location}}</p>
    <h3>Students :</h3>

    {% for student in school_detail.students.all %}
    <p>
        {{student.name }} who is  {{student.age}} years old.
    </p>
    {%endfor%}
</div>
<div class="container">
    <p><a href="{%url 'basic_app:update' pk=school_detail.pk %}" class="btn btn-warning">
        Update
    </a></p>
</div>

<ol>
    {% for school in  schools %}
    <h2><li>{{school}}</li></h2>
    {%endfor%}
    </ol>
{%endblock%}

5.Django/ClassBaseView/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html"%}
{% block body_block%}
<h1>
    {% if not form.instance.pk %}
    Create School
    {%else%}
    Update School
    {%endif %}
</h1>

<form method="POST">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{%endblock%}

5.Django/ClassBaseView/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html"%}
{% block body_block%}
<h1>Welcome to a list of all schools!</h1>
<ol>
    {% for school in  schools %}
    <h2><li> <a href="{{school.id}}"> {{school}} </a></li></h2>
    {%endfor%}
    </ol>
{%endblock%}

5.Django/ClassBaseView/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
      CBVs
      {# Title Extensions go inside the block#}
      {% block title_block %}

      {% endblock %}
    </title>

    {# Bootstrap and CSS (Probably would want downloaded files in your real projects)#}
    {# https://bootswatch.com/#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="#"></a>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

  {# Plugins#}


  <!-- Latest compiled and minified jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</html>

5.Django/ClassBaseView/templates/index.html
{% extends "base.html" %}

  {% block body_block %}
    <div class="jumbotron">
      <h1>Home Page!</h1>
    </div>
  {% endblock %}