5.Django/template_project/demo_app/urls.py
from django.urls import path
from demo_app import views


app_name='demo_app'

urlpatterns = [
    path('',views.index,name='index'),
    path('other/',views.other,name='other'),
]

5.Django/template_project/template_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('demo_app.urls')),
]

5.Django/template_project/demo_app/models.py
from django.db import models

# Create your models here.

5.Django/template_project/demo_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'harshit jaiswal','number':101}
    return render(request,'demo_app/index.html',context_dict)

    
def other(request):
    return render(request,'demo_app/others.html')

5.Django/template_project/templates/demo_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
   
    <title>Nav Bar</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


  <div class="container">

        {% block body_block%}
        
        {%endblock%}
  </div> 
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
</body>
</html>

5.Django/template_project/templates/demo_app/index.html
<!DOCTYPE html>
{%extends "demo_app/base.html"%}
{%load my_extras%}



{%block body_block %}
    <h1>This is index page</h1>
    <a href="{% url 'demo_app:other'%}">Go to other Page</a>
    <br>
    <a href="{% url 'admin:index' %}">Go to Admin Page</a>
    <br>
    <p>I am {{text|my_str_reverse}}  and my lucky number is {{number}}</p>
{%endblock%} 

5.Django/template_project/templates/demo_app/others.html
<!DOCTYPE html>
{%extends "demo_app/base.html"%}

{%block body_block %}
        <h1>This is others page</h1>
        <a href="{% url 'demo_app:index'%}">back to index page</a>
{%endblock%}